name: Scandio
options:
  bundleIdPrefix: pro.siemion
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  developmentLanguage: en
settings:
  base:
    SWIFT_VERSION: "5.9"
targets:
  Scandio:
    type: application
    platform: iOS
    sources:
      - path: Scandio
        excludes:
          - "Info.plist"
    settings:
      base:
        INFOPLIST_FILE: Scandio/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: pro.siemion.Scandio
        PRODUCT_NAME: Scandio
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        DEVELOPMENT_TEAM: ""
